upgraded infura keys
unstoppabledomains/resolution-java pull request #32
Opened 2021-02-09 13:00 UTC by JohnnyJumper

CNS_DEFAULT_URL -> using secured CNS key from UD. The key is whitelisted to use with only our contracts.
ENS_DEFAULT_URL -> using an unsecured public key for ENS only. This key will be removed once whitelisting issue resolves

2021-02-09 13:25 UTC, hivtushok approved these changes

2021-02-10 14:52 UTC, DeRain requested changes
@JohnnyJumper Make sure CI is running and README updated accordingly. We want to say explicitly, that we're using Infura without rate limits restrictions for CNS.

For ENS resolution it's recommended to setup own provider since we don't guarantee ENS Infura key availability.

2021-02-10 15:15 UTC, DeRain requested changes

2021-02-10 15:15 UTC, DeRain commented on src/main/java/com/unstoppabledomains/resolution/Resolution.java
>              put(NamingServiceType.ZNS, new ZNS(new NSConfig(Network.MAINNET, ZILLIQA_DEFAULT_URL), provider));
@JohnnyJumper Can we add ability to change ZILLIQA url as well?

2021-02-16 16:23 UTC, merged