Add .getRecord()
unstoppabledomains/resolution-java pull request #36
Opened 2021-03-02 05:15 UTC by sudoryan

Adds .getRecord() method to resolution class to allow for lookups of specific records.

2021-03-02 17:30 UTC, DeRain requested changes
@sudoryan Add tests please

2021-03-02 18:46 UTC, JohnnyJumper requested changes
minor change, but looks good

2021-03-02 18:46 UTC, JohnnyJumper commented on src/main/java/com/unstoppabledomains/resolution/Resolution.java
> +        }
This seems not really needed. we can probably simplify it and let the error pass by. 
```suggestion
        NamingService service = findService(domain);
        return service.getRecord(domain, recordKey);
```

2021-03-03 02:22 UTC, JohnnyJumper approved these changes

2021-03-03 10:37 UTC, hivtushok approved these changes

2021-03-05 18:07 UTC, merged