isSupported() calls registry.exists()
unstoppabledomains/resolution-java pull request #50
Opened 2021-06-29 04:24 UTC by sudoryan

2021-06-29 04:34 UTC, sudoryan commented
Includes commits from #49

2021-07-05 10:20 UTC, DeRain requested changes
Add tests for new TLD's.

2021-07-05 10:20 UTC, DeRain commented on src/main/java/com/unstoppabledomains/resolution/naming/service/UNS.java
> +      tokenID = tokenID(split[split.length - 1]);
Try to avoid collisions in variable and method namings

2021-07-05 10:20 UTC, DeRain commented on src/main/java/com/unstoppabledomains/resolution/naming/service/UNS.java
> +    } catch (Exception e) {
I don't think it's a good idea to catch any exception. Please, specify what types of exceptions could mean that domain is not supported

2021-07-06 21:09 UTC, merged